import type { Metadata } from "next";
import { notFound, redirect } from "next/navigation";
import { requireUser } from "@/lib/auth";
import { getSessionBundle } from "@/lib/data/diagnosis";
import { pendingQuestion } from "@/lib/diagnosis/service";
import { DiagnosisRunner } from "./diagnosis-runner";
import type { DiagnosisStep } from "@/lib/actions/diagnosis";

export const metadata: Metadata = { title: "진단" };

export default async function DiagnosisPage({
  params,
}: {
  params: Promise<{ projectId: string; sessionId: string }>;
}) {
  const { projectId, sessionId } = await params;
  const user = await requireUser();
  const { session, project, answers } = await getSessionBundle(sessionId, user.id);

  if (session.project_id !== projectId) notFound();
  if (session.status === "completed") {
    redirect(`/projects/${projectId}/diagnosis/${sessionId}/result`);
  }

  const pending = pendingQuestion(answers);
  const askedCount = answers.filter((row) => row.answer !== null).length;

  // The first question is generated by the client on mount — generating it here
  // would make rendering a side effect.
  const initialStep: DiagnosisStep | null = pending
    ? {
        type: "question",
        question: {
          id: pending.id,
          orderIndex: pending.order_index,
          question: pending.question,
          reason: pending.question_reason,
          questionType: pending.question_type,
          options: pending.options ?? [],
        },
        askedCount,
        maxQuestions: session.max_questions,
      }
    : null;

  return (
    <div className="mx-auto max-w-2xl">
      <DiagnosisRunner
        sessionId={session.id}
        projectId={projectId}
        projectName={project.name}
        maxQuestions={session.max_questions}
        initialAskedCount={askedCount}
        initialStep={initialStep}
        sessionStatus={session.status}
        sessionError={session.error_message}
      />
    </div>
  );
}
