-- Starter resource catalogue.
-- Small and hand-curated: the recommender matches on stage_tags / bottleneck_tags.
insert into public.resources (title, description, url, resource_type, stage_tags, bottleneck_tags)
values
  ('The Mom Test',
   '고객 인터뷰에서 칭찬이 아닌 사실을 얻어내는 질문법. 문제 검증 인터뷰를 처음 설계할 때 기준서로 쓴다.',
   'https://www.momtestbook.com/',
   'book',
   array['problem', 'solution'],
   array['problem_evidence', 'customer_definition', 'interview_quality']),

  ('Lean Canvas (Leanstack)',
   '문제·고객·해결책·지표를 한 장으로 정리해 검증되지 않은 가정을 드러내는 캔버스.',
   'https://leanstack.com/',
   'framework',
   array['problem', 'solution', 'validation'],
   array['problem_evidence', 'customer_definition', 'solution_fit']),

  ('Value Proposition Canvas (Strategyzer)',
   '고객의 과업·불만·기대와 제품 기능을 1:1로 매핑해 solution fit 가설을 구체화한다.',
   'https://www.strategyzer.com/',
   'framework',
   array['solution', 'validation'],
   array['solution_fit', 'positioning', 'customer_definition']),

  ('Y Combinator Startup Library',
   '고객 대화, MVP 범위, 초기 성장에 대한 창업자용 아티클/영상 모음.',
   'https://www.ycombinator.com/library',
   'article',
   array['problem', 'solution', 'validation', 'pmf'],
   array['problem_evidence', 'mvp_scope', 'acquisition']),

  ('The Lean Startup',
   'Build-Measure-Learn 루프와 검증된 학습(validated learning)의 원전. 실험 단위를 정의할 때 참고한다.',
   'http://theleanstartup.com/',
   'book',
   array['problem', 'solution', 'validation'],
   array['experiment_design', 'mvp_scope', 'solution_fit']),

  ('Concierge / Wizard-of-Oz MVP 설계 템플릿',
   '제품을 만들기 전에 사람이 직접 수행해 수요와 가치를 검증하는 실험 형태. 개발 비용 없이 solution fit을 본다.',
   null,
   'template',
   array['solution', 'validation'],
   array['mvp_scope', 'solution_fit', 'willingness_to_pay']),

  ('Fake Door / Landing Page Test 템플릿',
   '실제 기능 없이 랜딩페이지와 CTA로 수요와 메시지를 검증하는 실험 설계 체크리스트.',
   null,
   'template',
   array['solution', 'validation'],
   array['acquisition', 'positioning', 'willingness_to_pay']),

  ('Sean Ellis PMF Survey',
   '"이 제품을 더 이상 못 쓰게 되면 어떨까?" 설문으로 PMF 신호를 정량화하는 방법(40% 기준).',
   null,
   'framework',
   array['pmf'],
   array['pmf_signal', 'retention', 'customer_definition']),

  ('Cohort Retention 분석 기본기',
   '가입 코호트별 잔존율을 그려 리텐션이 평평해지는 구간이 있는지 확인한다. PMF 판단의 핵심 지표.',
   null,
   'article',
   array['pmf', 'growth'],
   array['retention', 'pmf_signal', 'activation']),

  ('Pirate Metrics (AARRR)',
   '획득·활성화·잔존·수익·추천 단계로 퍼널을 나눠 어디서 새는지 특정한다.',
   null,
   'framework',
   array['pmf', 'growth'],
   array['acquisition', 'activation', 'retention', 'monetization']),

  ('Van Westendorp 가격 민감도 조사',
   '4개 질문으로 수용 가능한 가격대를 추정한다. 지불 의사 검증 실험의 출발점.',
   null,
   'framework',
   array['validation', 'pmf'],
   array['willingness_to_pay', 'pricing', 'monetization']),

  ('Pre-sale / LOI 실험 가이드',
   '선결제, 계약 의향서(LOI)로 "말로만 사겠다"와 실제 지불 의사를 구분한다.',
   null,
   'template',
   array['validation', 'pmf'],
   array['willingness_to_pay', 'pricing', 'monetization']),

  ('사용자 온보딩 관찰(Usability Session) 체크리스트',
   '신규 사용자 5명의 첫 사용 과정을 관찰해 활성화 이탈 지점을 찾는다.',
   null,
   'template',
   array['validation', 'pmf'],
   array['activation', 'solution_fit', 'mvp_scope']),

  ('Traction: 19가지 채널 프레임워크',
   '채널을 넓게 탐색한 뒤 하나에 집중하는 Bullseye 프레임워크. 획득 병목에 사용.',
   null,
   'book',
   array['pmf', 'growth'],
   array['acquisition', 'channel', 'positioning']),

  ('Amplitude / PostHog 제품 분석 도입',
   '가입·활성화·재방문 이벤트를 계측해 정성 판단을 데이터로 대체한다.',
   'https://posthog.com/',
   'tool',
   array['validation', 'pmf', 'growth'],
   array['measurement', 'activation', 'retention']),

  ('실험 설계 1페이저 템플릿',
   '가설 / 방법 / 성공 기준 / 기간을 한 장에 적어 실험이 판단 가능한지 사전에 점검한다.',
   null,
   'template',
   array['problem', 'solution', 'validation', 'pmf', 'growth'],
   array['experiment_design', 'measurement']);

-- 실험을 "실행"하는 데 필요한 전문가와 도구.
-- 특정 업체나 개인을 지목하지 않고, 어떤 역할을 어디서 구하면 되는지를 기술한다.
insert into public.resources (title, description, url, resource_type, stage_tags, bottleneck_tags)
values
  ('고객 인터뷰 리서처 (UX 리서처)',
   '인터뷰 스크립트 설계와 진행을 대신해 준다. 창업자가 직접 물으면 유도 질문이 되기 쉬운 초기 문제 검증에 특히 값이 있다. 프리랜서 매칭 플랫폼이나 업계 커뮤니티에서 단건으로 섭외할 수 있다.',
   null,
   'expert',
   array['problem', 'solution'],
   array['problem_evidence', 'interview_quality', 'customer_definition']),

  ('도메인 실무자 (타깃 업계 종사자)',
   '타깃 고객과 같은 일을 하는 사람 1~2명을 자문으로 붙인다. 인터뷰 대상자 소개와 용어·업무 흐름 검증을 동시에 해결할 수 있어 초기 리크루팅 비용을 크게 줄인다.',
   null,
   'expert',
   array['problem', 'solution', 'validation'],
   array['problem_evidence', 'customer_definition', 'positioning']),

  ('프로덕트 애널리스트',
   '무엇을 계측해야 실험의 성공 기준을 판정할 수 있는지 설계해 준다. 지표가 없어 실험 결과를 해석하지 못하는 상황을 막는다.',
   null,
   'expert',
   array['validation', 'pmf', 'growth'],
   array['measurement', 'activation', 'retention', 'experiment_design']),

  ('그로스 마케터 / 퍼포먼스 마케터',
   '획득 채널 실험을 설계하고 소액 예산으로 채널별 반응을 비교해 준다. 채널을 넓게 벌려야 하는 시점에 단기 계약으로 쓴다.',
   null,
   'expert',
   array['pmf', 'growth'],
   array['acquisition', 'channel', 'positioning']),

  ('가격 전략 자문',
   '가격 실험 설계와 지불 의사 검증 방법을 잡아 준다. 무료 사용자만 모으고 매출 가설을 검증하지 못하는 상태를 벗어날 때 쓴다.',
   null,
   'expert',
   array['validation', 'pmf'],
   array['willingness_to_pay', 'pricing', 'monetization']),

  ('노코드 빌더 / 프리랜스 개발자',
   '검증용 MVP를 짧게 만들어 준다. 실험이 목적이므로 확장성이 아니라 기간과 폐기 가능성을 기준으로 섭외한다.',
   null,
   'expert',
   array['solution', 'validation'],
   array['mvp_scope', 'solution_fit']),

  ('인터뷰 일정 조율 도구 (Calendly 등)',
   '인터뷰 대상자에게 링크 하나만 보내 일정을 잡는다. 인터뷰 8건을 2주 안에 끝내야 할 때 가장 먼저 새는 시간을 막아 준다.',
   'https://calendly.com/',
   'tool',
   array['problem', 'solution'],
   array['problem_evidence', 'interview_quality']),

  ('화상 인터뷰 녹화 · 자동 전사',
   '인터뷰를 녹화하고 텍스트로 옮겨 둔다. 기억이 아니라 인용 가능한 원문이 남아야 근거로 쓸 수 있다.',
   null,
   'tool',
   array['problem', 'solution', 'validation'],
   array['problem_evidence', 'interview_quality', 'customer_feedback']),

  ('설문 도구 (Google Forms · Typeform 등)',
   '문제 빈도나 현재 지불 비용처럼 수치로 모아야 하는 항목을 짧은 설문으로 받는다.',
   'https://www.google.com/forms/about/',
   'tool',
   array['problem', 'validation', 'pmf'],
   array['problem_evidence', 'pmf_signal', 'measurement']),

  ('랜딩페이지 빌더 (Framer · Carrd 등)',
   '개발 없이 하루 만에 랜딩페이지를 올려 수요와 메시지를 검증한다. Fake door 실험의 실행 도구.',
   'https://framer.com/',
   'tool',
   array['solution', 'validation'],
   array['acquisition', 'positioning', 'willingness_to_pay']),

  ('결제 링크 (Stripe Payment Links · 토스페이먼츠 등)',
   '제품이 완성되지 않아도 선결제를 받아 지불 의사를 행동으로 확인한다. 말이 아니라 결제가 근거다.',
   'https://stripe.com/payments/payment-links',
   'tool',
   array['validation', 'pmf'],
   array['willingness_to_pay', 'pricing', 'monetization']),

  ('제품 분석 도구 (PostHog · Amplitude 등)',
   '가입·활성화·재방문 이벤트를 계측해 실험의 성공 기준을 숫자로 판정한다.',
   'https://posthog.com/',
   'tool',
   array['validation', 'pmf', 'growth'],
   array['measurement', 'activation', 'retention']);
